# Generated by Django 4.2.7 on 2025-12-08 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('numero_en_expansion', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Incoloro', 'Incoloro')], max_length=20, null=True)),
                ('tipo_secundario', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Incoloro', 'Incoloro')], max_length=20, null=True)),
                ('hp', models.PositiveIntegerField(blank=True, null=True)),
                ('etapa', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('ETAPA1', 'Etapa 1'), ('ETAPA2', 'Etapa 2'), ('BEBE', 'Bebé'), ('MEGA', 'Mega'), ('EX', 'EX'), ('GX', 'GX'), ('V', 'V'), ('VMAX', 'VMAX'), ('VSTAR', 'V-ASTRO'), ('RADIANTE', 'Radiante'), ('LEYENDA', 'Leyenda'), ('PRIME', 'Prime')], max_length=20, null=True)),
                ('ataque_1_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ataque_1_dano', models.PositiveIntegerField(blank=True, null=True)),
                ('ataque_1_costo', models.CharField(blank=True, max_length=50, null=True)),
                ('ataque_1_descripcion', models.TextField(blank=True, null=True)),
                ('ataque_2_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ataque_2_dano', models.PositiveIntegerField(blank=True, null=True)),
                ('ataque_2_costo', models.CharField(blank=True, max_length=50, null=True)),
                ('ataque_2_descripcion', models.TextField(blank=True, null=True)),
                ('habilidad_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidad_descripcion', models.TextField(blank=True, null=True)),
                ('debilidad', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Incoloro', 'Incoloro')], max_length=20, null=True)),
                ('resistencia', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Incoloro', 'Incoloro')], max_length=20, null=True)),
                ('costo_retirada', models.CharField(blank=True, max_length=20, null=True)),
                ('rareza', models.CharField(choices=[('COMUN', 'Común'), ('INFREC', 'Infrecuente'), ('RARA', 'Rara'), ('RARA_HOLO', 'Rara Holo'), ('RARA_LUM', 'Rara Luminosa'), ('SHINING', 'Shining Holo'), ('ULTRA', 'Rara Ultra'), ('SECRETA', 'Rara Secreta'), ('VARIOC', 'Rara Holo Variocolor'), ('EX', 'Rara Holo EX'), ('NIVX', 'Rara Holo Niv.X'), ('PRIME', 'Rara Prime'), ('LEYENDA', 'Rara LEYENDA'), ('ACE', 'Rara ACE'), ('GX', 'Rara GX'), ('V', 'Rara Holo V'), ('VMAX', 'Rara Holo VMAX'), ('INCREIBLE', 'Rara Increíble'), ('VASTRO', 'Rara Holo V-ASTRO'), ('RADIANTE', 'Rara Radiante'), ('DOBLE', 'Rara Doble'), ('ILUSTRACION', 'Rara Ilustración'), ('ILUSTRACION_ESP', 'Rara Ilustración Especial'), ('HIPER', 'Rara Híper'), ('ASTACTICO', 'Rara AS TÁCTICO'), ('PROMO', 'Promo')], max_length=20)),
                ('condicion', models.CharField(choices=[('NM', 'Casi Perfecta (Near Mint)'), ('LP', 'Levemente Jugada (Lightly Played)'), ('MP', 'Moderadamente Jugada (Moderately Played)'), ('HP', 'Altamente Jugada (Heavily Played)'), ('D', 'Dañada (Damaged)')], default='NM', max_length=2)),
                ('es_holo', models.BooleanField(default=False)),
                ('es_reverso_holo', models.BooleanField(default=False)),
                ('primera_edicion', models.BooleanField(default=False)),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('JP', 'Japonés')], default='Español', max_length=20)),
                ('imagen_frontal', models.ImageField(upload_to='cartas/frontal/')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='cartas/trasera/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('coleccionable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ['expansion', 'numero_en_expansion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('publica', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='colecciones/portadas/')),
                ('total_cartas', models.PositiveIntegerField(default=0)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('total_cartas', models.PositiveIntegerField()),
                ('simbolo', models.ImageField(blank=True, null=True, upload_to='expansiones/simbolos/')),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
                'ordering': ['-fecha_lanzamiento'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('cantidad_reservada', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('en_promocion', models.BooleanField(default=False)),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('vendidos_total', models.PositiveIntegerField(default=0)),
                ('valoracion_promedio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('popularidad', models.IntegerField(default=0)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('carta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.carta')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CARRITO', 'En Carrito'), ('PEND', 'Pendiente'), ('PROC', 'En Proceso'), ('ENVI', 'Enviado'), ('ENTR', 'Entregado'), ('CANC', 'Cancelado'), ('REEM', 'Reembolsado')], default='CARRITO', max_length=10)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_envio', models.TextField()),
                ('ciudad_envio', models.CharField(max_length=100)),
                ('provincia_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais_envio', models.CharField(default='España', max_length=100)),
                ('metodo_pago', models.CharField(blank=True, choices=[('TARJ', 'Tarjeta de Crédito/Débito'), ('PAYP', 'PayPal'), ('TRANS', 'Transferencia Bancaria'), ('EFEC', 'Efectivo'), ('CRIPTO', 'Criptomoneda')], max_length=10, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_envio', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('notas_cliente', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='core.carta')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='core.inventario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ColeccionCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, choices=[('NM', 'Casi Perfecta (Near Mint)'), ('LP', 'Levemente Jugada (Lightly Played)'), ('MP', 'Moderadamente Jugada (Moderately Played)'), ('HP', 'Altamente Jugada (Heavily Played)'), ('D', 'Dañada (Damaged)')], max_length=2, null=True)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_colecciones', to='core.carta')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='core.coleccion')),
            ],
            options={
                'verbose_name': 'Carta en Colección',
                'verbose_name_plural': 'Cartas en Colecciones',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.AddField(
            model_name='carta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='carta',
            name='evolucion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='core.carta'),
        ),
        migrations.AddField(
            model_name='carta',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas', to='core.expansion'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveIntegerField(help_text='Valoración de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('condicion_recibida', models.CharField(blank=True, choices=[('NM', 'Casi Perfecta (Near Mint)'), ('LP', 'Levemente Jugada (Lightly Played)'), ('MP', 'Moderadamente Jugada (Moderately Played)'), ('HP', 'Altamente Jugada (Heavily Played)'), ('D', 'Dañada (Damaged)')], max_length=2, null=True)),
                ('recomendado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('util_si', models.PositiveIntegerField(default=0)),
                ('util_no', models.PositiveIntegerField(default=0)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.carta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['carta', 'aprobada'], name='core_resena_carta_i_0c2940_idx'), models.Index(fields=['valoracion'], name='core_resena_valorac_c1fb3b_idx')],
                'unique_together': {('carta', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='core_pedido_estado_404470_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='core_pedido_fecha_p_75831c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='core_pedido_cliente_bea0b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'carta')},
        ),
        migrations.AlterUniqueTogether(
            name='coleccioncarta',
            unique_together={('coleccion', 'carta')},
        ),
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['nombre'], name='core_carta_nombre_f9bdab_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['tipo'], name='core_carta_tipo_3630fa_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['rareza'], name='core_carta_rareza_8e1331_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['etapa'], name='core_carta_etapa_504e75_idx'),
        ),
    ]
