# Generated by Django 4.2.7 on 2025-12-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='subtotal',
        ),
    ]
