# Generated by Django 4.2.7 on 2025-12-08 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_coleccioncarta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='ciudad_envio',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='direccion_envio',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='notas_cliente',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pais_envio',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='ataque_1_dano',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='ataque_1_descripcion',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='ataque_1_nombre',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='provincia_envio',
        ),
        migrations.AddField(
            model_name='carta',
            name='popularidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carta',
            name='tipo_secundario',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Hielo', 'Hielo'), ('Lucha', 'Lucha'), ('Veneno', 'Veneno'), ('Tierra', 'Tierra'), ('Volador', 'Volador'), ('Psíquico', 'Psíquico'), ('Bicho', 'Bicho'), ('Roca', 'Roca'), ('Fantasma', 'Fantasma'), ('Dragón', 'Dragón'), ('Siniestro', 'Siniestro'), ('Acero', 'Acero'), ('Hada', 'Hada'), ('Incoloro', 'Incoloro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='colecciones/portadas/'),
        ),
        migrations.AddField(
            model_name='coleccioncarta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='valoracion_promedio',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='inventario',
            name='vendidos_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resena',
            name='condicion_recibida',
            field=models.CharField(blank=True, choices=[('NM', 'Casi Perfecta (Near Mint)'), ('LP', 'Levemente Jugada (Lightly Played)'), ('MP', 'Moderadamente Jugada (Moderately Played)'), ('HP', 'Altamente Jugada (Heavily Played)'), ('D', 'Dañada (Damaged)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='recomendado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='votos_negativos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resena',
            name='votos_positivos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carta',
            name='rareza',
            field=models.CharField(choices=[('COMUN', 'Común'), ('INFREC', 'Infrecuente'), ('RARA', 'Rara'), ('RARA_HOLO', 'Rara Holo'), ('RARA_LUM', 'Rara Luminosa'), ('ULTRA', 'Rara Ultra'), ('SECRETA', 'Rara Secreta'), ('EX', 'Rara Holo EX'), ('GX', 'Rara GX'), ('V', 'Rara Holo V'), ('VMAX', 'Rara Holo VMAX'), ('PROMO', 'Promo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coleccioncarta',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_colecciones', to='core.carta'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='core.carta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'En Carrito'), ('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='CARRITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TARJETA', 'Tarjeta'), ('PAYPAL', 'PayPal'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='coleccioncarta',
            unique_together={('coleccion', 'carta')},
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'carta')},
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('carta', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['nombre'], name='core_carta_nombre_f9bdab_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['tipo'], name='core_carta_tipo_3630fa_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['rareza'], name='core_carta_rareza_8e1331_idx'),
        ),
        migrations.AddIndex(
            model_name='carta',
            index=models.Index(fields=['popularidad'], name='core_carta_popular_6fc903_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='core_pedido_estado_404470_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='core_pedido_fecha_p_75831c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='core_pedido_cliente_bea0b9_idx'),
        ),
    ]
