# Generated by Django 4.2.7 on 2025-12-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
